#!/bin/bash
# Hytale Server Startup Script - Static Lobby
# Generated by Numdrassl Server Manager

MEMORY="${MEMORY:-2G}"
SERVER_JAR="${SERVER_JAR:-server.jar}"

JVM_OPTS=(
    "-Xms${MEMORY}"
    "-Xmx${MEMORY}"
    "-XX:+UseG1GC"
    "-XX:+ParallelRefProcEnabled"
    "-XX:MaxGCPauseMillis=200"
    "-Djava.net.preferIPv4Stack=true"
    "-Dfile.encoding=UTF-8"
)

if [ -n "$NUMDRASSL_SERVER_ID" ]; then
    JVM_OPTS+=("-Dnumdrassl.server.id=${NUMDRASSL_SERVER_ID}")
fi

echo "Starting Static Lobby server..."
exec java "${JVM_OPTS[@]}" -jar "${SERVER_JAR}" "$@"
