#!/bin/bash
# Hytale Server Startup Script - Bedwars
# Generated by Numdrassl Server Manager

# Configuration
MEMORY="${MEMORY:-2G}"
SERVER_JAR="${SERVER_JAR:-server.jar}"

# JVM Options
JVM_OPTS=(
    "-Xms${MEMORY}"
    "-Xmx${MEMORY}"
    "-XX:+UseG1GC"
    "-XX:+ParallelRefProcEnabled"
    "-XX:MaxGCPauseMillis=200"
    "-XX:+UnlockExperimentalVMOptions"
    "-XX:+DisableExplicitGC"
    "-XX:+AlwaysPreTouch"
    "-Djava.net.preferIPv4Stack=true"
    "-Dfile.encoding=UTF-8"
)

# Server ID from environment
if [ -n "$NUMDRASSL_SERVER_ID" ]; then
    JVM_OPTS+=("-Dnumdrassl.server.id=${NUMDRASSL_SERVER_ID}")
fi

# Port from environment
if [ -n "$NUMDRASSL_PORT" ]; then
    JVM_OPTS+=("-Dnumdrassl.server.port=${NUMDRASSL_PORT}")
fi

echo "Starting Bedwars server..."
echo "Memory: ${MEMORY}"
echo "Server ID: ${NUMDRASSL_SERVER_ID:-unknown}"
echo "Port: ${NUMDRASSL_PORT:-unknown}"

# Start the server
exec java "${JVM_OPTS[@]}" -jar "${SERVER_JAR}" "$@"
