#!/bin/bash
# Hytale Server Startup Script
# Generated by Numdrassl Server Manager

# Configuration
MEMORY="${MEMORY:-2G}"
SERVER_JAR="${SERVER_JAR:-server.jar}"

# JVM Options for optimal Hytale server performance
JVM_OPTS=(
    "-Xms${MEMORY}"
    "-Xmx${MEMORY}"
    "-XX:+UseG1GC"
    "-XX:+ParallelRefProcEnabled"
    "-XX:MaxGCPauseMillis=200"
    "-XX:+UnlockExperimentalVMOptions"
    "-XX:+DisableExplicitGC"
    "-XX:+AlwaysPreTouch"
    "-XX:G1NewSizePercent=30"
    "-XX:G1MaxNewSizePercent=40"
    "-XX:G1HeapRegionSize=8M"
    "-XX:G1ReservePercent=20"
    "-XX:G1HeapWastePercent=5"
    "-XX:G1MixedGCCountTarget=4"
    "-XX:InitiatingHeapOccupancyPercent=15"
    "-XX:G1MixedGCLiveThresholdPercent=90"
    "-XX:G1RSetUpdatingPauseTimePercent=5"
    "-XX:SurvivorRatio=32"
    "-XX:+PerfDisableSharedMem"
    "-XX:MaxTenuringThreshold=1"
    "-Djava.net.preferIPv4Stack=true"
    "-Dfile.encoding=UTF-8"
)

# Server ID from environment (set by Numdrassl)
if [ -n "$NUMDRASSL_SERVER_ID" ]; then
    JVM_OPTS+=("-Dnumdrassl.server.id=${NUMDRASSL_SERVER_ID}")
fi

# Port from environment
if [ -n "$NUMDRASSL_PORT" ]; then
    JVM_OPTS+=("-Dnumdrassl.server.port=${NUMDRASSL_PORT}")
fi

echo "Starting Hytale server..."
echo "Memory: ${MEMORY}"
echo "Server JAR: ${SERVER_JAR}"
echo "Server ID: ${NUMDRASSL_SERVER_ID:-unknown}"

# Start the server
exec java "${JVM_OPTS[@]}" -jar "${SERVER_JAR}" "$@"
