#!/bin/bash
# Hytale Server Startup Script - Skywars
# Generated by Numdrassl Server Manager

MEMORY="${MEMORY:-2G}"
SERVER_JAR="${SERVER_JAR:-server.jar}"

JVM_OPTS=(
    "-Xms${MEMORY}"
    "-Xmx${MEMORY}"
    "-XX:+UseG1GC"
    "-XX:+ParallelRefProcEnabled"
    "-XX:MaxGCPauseMillis=200"
    "-Djava.net.preferIPv4Stack=true"
    "-Dfile.encoding=UTF-8"
)

if [ -n "$NUMDRASSL_SERVER_ID" ]; then
    JVM_OPTS+=("-Dnumdrassl.server.id=${NUMDRASSL_SERVER_ID}")
fi

if [ -n "$NUMDRASSL_PORT" ]; then
    JVM_OPTS+=("-Dnumdrassl.server.port=${NUMDRASSL_PORT}")
fi

echo "Starting Skywars server..."
echo "Memory: ${MEMORY}"
echo "Server ID: ${NUMDRASSL_SERVER_ID:-unknown}"
echo "Port: ${NUMDRASSL_PORT:-unknown}"

exec java "${JVM_OPTS[@]}" -jar "${SERVER_JAR}" "$@"
